# Generated by Django 6.1.1 on 2026-09-28 04:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0005_alter_message_input"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemPrompy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("order_number", models.IntegerField(default=0)),
                ("prompt", models.TextField(max_length=10000)),
                (
                    "create_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "update_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
        ),
    ]
