# Generated by Django 6.1.1 on 2026-09-28 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0006_systemprompy"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="SystemPrompy",
            new_name="SystemPrompt",
        ),
    ]
